// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type FilesIndex struct {
	ID           int64  `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	Path         string `json:"path"`
	Lines        int64  `json:"lines"`
}

type Repository struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Branch    string    `json:"branch"`
	UpdatedAt time.Time `json:"updated_at"`
	IndexedAt time.Time `json:"indexed_at"`
	HadError  bool      `json:"had_error"`
}
